### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by ghost** [abursavich/nett#4]
Would it be possible to add Redis as a caching backend (or something that allows for auto-expiring of keys)? On a long-running instance the map can build up & take memory. I suppose this could be done by an interface and at startup you choose either a map or Redis, etc. Thanks for building this, btw! It has come in very handy.

**Comment by abursavich** [comment]
I'd be happy to change CacheResolver to make it more useful -- maybe add size constraints or proactively collect expired items. When I wrote this, my use case was to cache the lookups of a small fixed set of addresses. However, I wouldn't want to add Redis dependencies to this package. Resolver is an interface and a Redis-backed version could be implemented in a different package.

**Comment by ghost** [comment]
That is a good suggestion. I will work on another package and get that open-source. thanks you.
